[[sources]]
id = "youtinghao"
title = "游庭皓的財經皓角"
author = "游庭皓"
rss_url = "https://feeds.soundcloud.com/users/soundcloud:users:735679489/sounds.rss"

[[sources]]
id = "tech_wave"
title = "科技浪"
author = "哈利說"
rss_url = "https://feed.firstory.me/rss/user/cm3o5681s06e801v3fxpjehwb"

